services:
  db_blog:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: blogDB
    volumes:
      - blog_data:/var/lib/postgresql/data

  db_auth:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: authDB
    volumes:
      - auth_data:/var/lib/postgresql/data

  blog:
    image: derekshaw/blogmicro:1.1
    depends_on:
      - db_blog
    environment:
      DATABASE_URL: "postgresql://postgres:example@db_blog/blogDB"
    entrypoint: ["/app/wait-for.sh", "db_blog:5432", "--", "/app/start.sh"]
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
  
  auth:
    image: derekshaw/gatewaymicro:1.0
    ports:
      - "8080:8080"
    depends_on:
      - db_auth
    environment:
      DB_SOURCE: "postgresql://postgres:example@db_auth/authDB?sslmode=disable"
      BLOG_MICRO_URL: "http://blog:8000"
      GIN_MODE: "release"
    entrypoint: ["/app/wait-for.sh", "db_auth:5432", "--", "/app/start.sh"]
    command: ["/app/main"]


volumes:
  blog_data:
  auth_data:
