services:
  db:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: blogDB
    volumes:
      - db_data:/var/lib/postgresql/data

  blog:
    image: derekshaw/blogmicro:1.0
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:example@db/blogDB"
    entrypoint: ["/app/wait-for.sh", "db:5432", "--", "/app/start.sh"]
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  db_data:
