name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      # - uses: actions/checkout@v3
      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}
      #
      - name: Install dependencies
        run: |
          make install
          make install-pytest

      - name: Run tests
        run: |
          make test
